### ISSUE TITLE
missing db.csv

### ISSUE THREAD

**Issue by Nikoleta-v3** [Axelrod-Python/Axelrod-fingerprint#7]
```
Traceback (most recent call last):
  File "update_fingerprints.py", line 152, in <module>
    main(turns, repetitions)
  File "update_fingerprints.py", line 137, in main
    db = read_db()
  File "update_fingerprints.py", line 43, in read_db
    with open(filename, "r") as db:
FileNotFoundError: [Errno 2] No such file or directory: 'db.csv'
```

This is because of line `137` in `update_fingerprints.py`.  We can have a check if file exists and if not create an empty with only the headers but is up to you.

**Comment by drvinceknight** [comment]
Good idea on the check and create an empty one. :+1:

**Comment by Nikoleta-v3** [comment]
I will take this issue.

**Comment by drvinceknight** [comment]
You can use try and except on the `FileNotFoundError`
